/**
 * SPMS shared theme – single source for colors, spacing, and common styles.
 * Use everywhere so the project has one consistent look.
 */

import type { CSSProperties } from "react";

export const theme = {
  colors: {
    primary: "#2563eb",
    primaryDark: "#1d4ed8",
    secondary: "#64748b",
    secondaryDark: "#475569",
    background: "#f1f5f9",
    surface: "#ffffff",
    surfaceAlt: "#f8fafc",
    text: "#1e293b",
    textMuted: "#64748b",
    border: "#cbd5e1",
    borderLight: "#e2e8f0",
    header: "#1f2937",
    sidebar: "#e2e8f0",
    success: "#16a34a",
    error: "#b91c1c",
    danger: "#dc2626",
    teal: "#0f766e",
  },
  font: {
    family: "Segoe UI, system-ui, sans-serif",
    size: { sm: "13px", base: "14px", lg: "16px", xl: "18px", title: "20px" },
    weight: { normal: 400, medium: 500, semibold: 600, bold: 700 },
  },
  spacing: { xs: 4, sm: 8, md: 12, lg: 16, xl: 20, xxl: 24 },
  radius: { sm: 6, md: 8, lg: 10, xl: 12 },
  shadow: "0 1px 3px rgba(0,0,0,0.08)",
  shadowLg: "0 10px 25px rgba(0,0,0,0.1)",
} as const;

type Theme = typeof theme;

export const styles = {
  pageWrap: (): CSSProperties => ({
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    backgroundColor: theme.colors.background,
    fontFamily: theme.font.family,
  }),
  mainContent: (): CSSProperties => ({
    flex: 1,
    padding: theme.spacing.xl,
    backgroundColor: theme.colors.background,
  }),
  card: (): CSSProperties => ({
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl,
    boxShadow: theme.shadowLg,
    border: `1px solid ${theme.colors.borderLight}`,
    padding: theme.spacing.xxl,
  }),
  pageCard: (): CSSProperties => ({
    maxWidth: 900,
    margin: "0 auto",
    padding: theme.spacing.xl,
    backgroundColor: theme.colors.surfaceAlt,
    fontFamily: theme.font.family,
  }),
  title: (): CSSProperties => ({
    fontSize: theme.font.size.title,
    fontWeight: theme.font.weight.bold,
    color: theme.colors.text,
    margin: 0,
    marginBottom: theme.spacing.lg,
  }),
  subtitle: (): CSSProperties => ({
    fontSize: theme.font.size.base,
    color: theme.colors.textMuted,
    marginBottom: theme.spacing.xl,
  }),
  input: (): CSSProperties => ({
    width: "100%",
    padding: "10px 12px",
    fontSize: theme.font.size.base,
    color: theme.colors.text,
    backgroundColor: theme.colors.surface,
    border: `1px solid ${theme.colors.border}`,
    borderRadius: theme.radius.sm,
    boxSizing: "border-box",
  }),
  label: (): CSSProperties => ({
    display: "block",
    fontSize: theme.font.size.base,
    fontWeight: theme.font.weight.medium,
    color: theme.colors.text,
    marginBottom: theme.spacing.xs,
  }),
  btnPrimary: (): CSSProperties => ({
    backgroundColor: theme.colors.primary,
    color: "#fff",
    padding: "10px 16px",
    border: "none",
    borderRadius: theme.radius.sm,
    cursor: "pointer",
    fontWeight: theme.font.weight.medium,
    fontSize: theme.font.size.base,
  }),
  btnSecondary: (): CSSProperties => ({
    backgroundColor: theme.colors.secondary,
    color: "#fff",
    padding: "10px 16px",
    border: "none",
    borderRadius: theme.radius.sm,
    cursor: "pointer",
    fontWeight: theme.font.weight.medium,
    fontSize: theme.font.size.base,
  }),
  btnDanger: (): CSSProperties => ({
    backgroundColor: theme.colors.danger,
    color: "#fff",
    padding: "6px 10px",
    border: "none",
    borderRadius: theme.radius.sm,
    cursor: "pointer",
    fontWeight: theme.font.weight.medium,
    fontSize: theme.font.size.base,
  }),
  btnTeal: (): CSSProperties => ({
    backgroundColor: theme.colors.teal,
    color: "#fff",
    padding: "6px 10px",
    border: "none",
    borderRadius: theme.radius.sm,
    cursor: "pointer",
    fontWeight: theme.font.weight.medium,
    fontSize: theme.font.size.base,
  }),
  btnSuccess: (): CSSProperties => ({
    backgroundColor: theme.colors.success,
    color: "#fff",
    padding: "6px 10px",
    border: "none",
    borderRadius: theme.radius.sm,
    cursor: "pointer",
    fontWeight: theme.font.weight.medium,
    fontSize: theme.font.size.base,
  }),
  btnWrap: (): CSSProperties => ({
    display: "flex",
    gap: theme.spacing.md,
    marginTop: theme.spacing.lg,
  }),
  table: (): CSSProperties => ({
    width: "100%",
    borderCollapse: "collapse" as const,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.sm,
    overflow: "hidden",
    boxShadow: theme.shadow,
  }),
  th: (): CSSProperties => ({
    padding: theme.spacing.md,
    textAlign: "left",
    fontWeight: theme.font.weight.semibold,
    color: theme.colors.text,
    borderBottom: `2px solid ${theme.colors.border}`,
    backgroundColor: theme.colors.sidebar,
  }),
  td: (): CSSProperties => ({
    padding: theme.spacing.md,
    textAlign: "center",
    color: theme.colors.text,
    borderBottom: `1px solid ${theme.colors.borderLight}`,
  }),
  /** Full-page layout: header top, content middle, footer bottom – no floating content */
  layoutWrapper: (): CSSProperties => ({
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    backgroundColor: theme.colors.background,
  }),
  layoutHeader: (): CSSProperties => ({
    flexShrink: 0,
  }),
  layoutBody: (): CSSProperties => ({
    flex: 1,
    display: "flex",
    minHeight: 0,
    width: "100%",
  }),
  layoutMain: (): CSSProperties => ({
    flex: 1,
    padding: theme.spacing.xl,
    backgroundColor: theme.colors.background,
    overflow: "auto",
    minWidth: 0,
  }),
  layoutFooter: (): CSSProperties => ({
    flexShrink: 0,
  }),
  headerBar: (): CSSProperties => ({
    backgroundColor: theme.colors.header,
    color: "#fff",
    padding: "16px 24px",
    minHeight: 56,
    fontSize: theme.font.size.title,
    fontWeight: theme.font.weight.bold,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
  }),
  footerBar: (): CSSProperties => ({
    backgroundColor: theme.colors.header,
    color: "#fff",
    padding: "12px 24px",
    minHeight: 48,
    textAlign: "center",
    fontSize: theme.font.size.base,
    boxShadow: "0 -2px 4px rgba(0,0,0,0.1)",
  }),
  sidebar: (): CSSProperties => ({
    width: 250,
    backgroundColor: theme.colors.sidebar,
    padding: theme.spacing.lg,
  }),
  sidebarLink: (): CSSProperties => ({
    display: "block",
    padding: "10px 12px",
    color: theme.colors.text,
    textDecoration: "none",
    borderRadius: theme.radius.sm,
    marginBottom: theme.spacing.sm,
    backgroundColor: theme.colors.surfaceAlt,
  }),
  actionsRow: (): CSSProperties => ({
    display: "flex",
    gap: theme.spacing.sm,
    justifyContent: "center",
    flexWrap: "nowrap" as const,
  }),
  pageHeader: (): CSSProperties => ({
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: theme.spacing.lg,
  }),
  addButton: (): CSSProperties => ({
    ...styles.btnPrimary(),
    padding: "8px 14px",
  }),
  /** Wrapper for edit/add forms – same look across the project */
  formCard: (): CSSProperties => ({
    ...styles.card(),
    maxWidth: 500,
    margin: "0 auto",
    padding: theme.spacing.xl,
    fontFamily: theme.font.family,
  }),
  /** Textarea matching input colors so text is visible */
  textarea: (): CSSProperties => ({
    ...styles.input(),
    minHeight: 80,
    resize: "vertical",
  }),
  /** Checkbox label row */
  checkboxRow: (): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: theme.spacing.sm,
    marginBottom: theme.spacing.lg,
    cursor: "pointer",
    color: theme.colors.text,
    fontSize: theme.font.size.base,
  }),
} as const;

export default theme;
